# Generated by Django 4.1.5 on 2023-01-07 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_ip_pub_date_alter_ip_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ip',
            name='ip_address',
            field=models.GenericIPAddressField(default=0),
        ),
    ]
