# Generated by Django 4.1.5 on 2023-01-08 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_blocklistip_iplog_delete_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blocklistip',
            name='ip',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='iplog',
            name='ip_address',
            field=models.TextField(max_length=20),
        ),
    ]
