# Generated by Django 4.1.5 on 2023-01-24 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
